"""Pydantic v2 schemas for the AI proxy microservice endpoint."""

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field


class UserRole(str, Enum):
    """Roles recognised by the Unnitro platform."""

    STUDENT = "student"
    FACULTY = "faculty"
    ADMIN = "admin"


class AIQueryRequest(BaseModel):
    """Inbound payload for the AI query proxy."""

    prompt: str = Field(
        ...,
        min_length=1,
        max_length=4096,
        description="User's natural-language query",
    )
    user_uid: str = Field(..., description="Firebase UID of the requesting user")
    role: UserRole = Field(UserRole.STUDENT, description="Caller's platform role")
    context_flags: dict[str, str] = Field(
        default_factory=dict,
        description="Optional key-value context hints for the AI engine",
    )


class AIQueryResponse(BaseModel):
    """Response envelope returned by the AI proxy."""

    status: str = Field(
        ...,
        description=(
            "Outcome indicator: 'ok', 'fallback_timeout', or 'service_unreachable'"
        ),
    )
    answer: str = Field(..., description="AI-generated answer text")
    model: str = Field("unknown", description="Model that produced the answer")
    is_fallback: bool = Field(
        False,
        description="True when the answer was generated by the local fallback path",
    )
    tools_used: list[str] = Field(
        default_factory=list,
        description="List of tool identifiers invoked during generation",
    )
    latency_ms: float = Field(
        0.0,
        ge=0.0,
        description="Round-trip time to the downstream AI service in milliseconds",
    )
